### ISSUE TITLE
Another hover animation

### ISSUE THREAD

**Issue by shiningshani** [Design-and-Code/css-buttons#23]
I want to add a beautiful hover effect. Can I contribute??

**Comment by Rajkumar-justcoder** [comment]
Yup! Why not.

**Comment by shiningshani** [comment]
Bro I was working to add a button since issue creation.  It was taking some time because it was going to be my first good PR. 
As of now I am ready to pull request but what I see is the issue being closed. 
Should I create new issue ? or 
Should I pull request directly ? or 
You will reopen this issue!! 

Being new to open-sourcing, I expect a positive answer.  :)

**Comment by Rajkumar-justcoder** [comment]
your button is there in site 
![image](https://user-images.githubusercontent.com/83064473/194857775-54da15c6-ede6-4bc1-a127-280860139b45.png)
https://css-buttons-hover.netlify.app/

**Comment by Rajkumar-justcoder** [comment]
yup there was one my mistake that i was merging so many pr so i forgot to write feedback there

**Comment by Rajkumar-justcoder** [comment]
i hope this would clear your doubts if there is still any then do let me know

**Comment by Rajkumar-justcoder** [comment]
sorry for that

**Comment by Rajkumar-justcoder** [comment]
i have re opened pr
