### ISSUE TITLE
Feat: Add eslint and prettier with .vscode folder for proper format

### ISSUE THREAD

**Issue by lostgirljourney** [Design-and-Code/css-buttons#3]
The title is self-explanatory and I want to work on this. @DevrajDC

**Comment by Rajkumar-justcoder** [comment]
### hey @lostgirljourney  we had already added .vscode files and folder in .gitignore so other than that you can work on eslint and prettier and you can add more buttons

**Comment by Rajkumar-justcoder** [comment]
yeah Cause it changes other peoples default settings of vscode if they use so added some things in .gitignore file for that

**Comment by lostgirljourney** [comment]
yes. i know about it.
