### ISSUE TITLE
I want to add Hover Animation Button 

### ISSUE THREAD

**Issue by minhaj-313** [Design-and-Code/css-buttons#38]
I want to add Hover Animative button.
Please assign me under hacktoberfest.
Thank You

**Comment by Rajkumar-justcoder** [comment]
Hey Yeah sure!!
Note: Pls follow rules declared in readme.md

**Comment by Mayank1170** [comment]
Hey!
i want to work on it, can you please assign this issue to me..
i'll try fix it within 8 hours.

**Comment by Rajkumar-justcoder** [comment]
Hey @Mayank1170  there is nothing to fix any thing 
But you can add button

**Comment by Mayank1170** [comment]
hey why did you delete my pull request ??

**Comment by Divyanshi2408** [comment]
Hey @ankit-kmar I want to add hover animation button Could you please assign me

**Comment by Divyanshi2408** [comment]
Hey I want to add hover animation button Could you please assign me

**Comment by Rajkumar-justcoder** [comment]
hey currently we are working on the project
so will assign later currently closing this issue
