### ISSUE TITLE
Hoven button addition 

### ISSUE THREAD

**Issue by vishal1patidar** [Design-and-Code/css-buttons#47]
In my mind two animation buttons are there I can contribute

**Comment by Rajkumar-justcoder** [comment]
Yeah Sure

**Comment by deepeshsharmaofficial** [comment]
I also want to add new button with animation.
Plz assign this issue to me and add hacktoberfest label to it.

**Comment by Rajkumar-justcoder** [comment]
> I also want to add new button with animation. Plz assign this issue to me and add hacktoberfest label to it.

Hacktoberfest lable is already added  
and yeah sure go ahead

**Comment by aaryan182** [comment]
I also want to add new button .

**Comment by Mayank1170** [comment]
hey!
i wanna work on it 
can you please assign it to me

**Comment by Rajkumar-justcoder** [comment]
> hey!
> i wanna work on it 
> can you please assign it to me
> 

Hey i have already assigned to u

**Comment by Rajkumar-justcoder** [comment]
> > hey!
> > i wanna work on it 
> > can you please assign it to me
> > 
> 
> Hey i have already assigned to u

Other issue
