### ISSUE TITLE
Add a favicon for the website

### ISSUE THREAD

**Issue by uday03meh** [Design-and-Code/css-buttons#56]
I want to add a favicon for this website so that it appears more professional and credible. Currently I have something like this in mind and we can change background colors. I can also explore and suggest different designs for favicon once this issue is assigned to me.

![image](https://user-images.githubusercontent.com/59679281/194415245-cd54ac92-8db2-4597-a627-b8c2a5c283f4.png)

**Comment by Rajkumar-justcoder** [comment]
No, It cant be assign cause it already decide what to add in favicon so will add it after hacktoberfest over
