### ISSUE TITLE
adding a button with my best animations

### ISSUE THREAD

**Issue by MohammadRehanPatel** [Design-and-Code/css-buttons#77]
assign me with Hacktoberfest tag please

**Comment by Rajkumar-justcoder** [comment]
> assign me with Hacktoberfest tag please

hey currently we are working on the project
so will assign later currently closing this issue

**Comment by MohammadRehanPatel** [comment]
Assign me with Hacktoberfest tag

**Comment by Rajkumar-justcoder** [comment]
then u have to make pr with in ist 10:am

**Comment by MohammadRehanPatel** [comment]
button added
