### ISSUE TITLE
Add some new attractive buttons

### ISSUE THREAD

**Issue by AdithiDesai** [Design-and-Code/css-buttons#86]
I want add new attractive animated CSS buttons

**Comment by AdithiDesai** [comment]
Hey, can you assign me this issue?

**Comment by Rajkumar-justcoder** [comment]
#78

**Comment by Pallavibahekar** [comment]
hey can you assign me this issue @Rajkumar-justcoder  under hacktoberfest 2022?

**Comment by Rajkumar-justcoder** [comment]
#78
